{
 "title": "ArangoDB",
 "description": "ArangoDB kubernetes dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(arangodb_process_statistics_user_time[15s])*22",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "arangodb_process_statistics_virtual_memory_size",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "nproc" }
   ],
   "targets": [
    {
     "expr": "arangodb_process_statistics_number_of_threads",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "arangodb_process_statistics_number_of_threads",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Client connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "arangodb_client_connection_statistics_client_connections",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Resident Set size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "arangodb_process_statistics_resident_set_size",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Agency write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(agency_agent_write_ok[15s])"
    }
   ]
  },
  {
   "title": "RocksDB sst file size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rocksdb_live_sst_files_size" }
   ]
  },
  {
   "title": "RocksDB cache access rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rocksdb_block_cache_usage[15s])"
    }
   ]
  }
 ]
}